# Qualitative Mathematical Modelling in Python

Author: Jayden Hyman

Version: 0.2.4

Email: j.hyman@uq.edu.au

📝 Getting started:

1. Install the QMM package: `%pip install qmm-core`, then comment out the line `%pip install qmm-core` with `#` at the start of the line, or simply delete the cell. Then restart the kernel from the menu bar.
2. Create a signed digraph using the web application: [Open in browser](https://d2x70551if0frn.cloudfront.net/).
3. Run the Python package and dependencies cell.
4. Import the signed digraph file (`.json`) using the `import_digraph` function (e.g., `import_digraph("folder/model.json")`). You can also use the `list_to_digraph` to create a signed digraph from a signed adjacency matrix (e.g., `list_to_digraph("[[-1,-1,0],[1,-1,-1],[0,1,-1]]")`).
5. Run each cell by pressing the keyboard shortcut "shift+enter" or the play icon (when hovering over a cell). 

The lake-mesocosm model from Hulot et al. (2000) is used as an example in this notebook.

Reference: Hulot, F.D., Lacroix, G., Lescher-Moutoué, F., Loreau, M., 2000. Functional diversity governs ecosystem response to nutrient enrichment. Nature 405, 340–344. https://doi.org/10.1038/35012591

In [ ]:
#%pip install qmm-core

In [3]:
#@title Python package and dependencies
from qmm import *
import sympy as sp
import pandas as pd
from IPython.display import display, Markdown, Math
sp.init_printing(use_latex='mathjax', mat_symbol_style='bold')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

## Model structure

In [6]:
G = import_digraph("test/mesocosm.json")
display(Math(r'^{\circ}\mathbf{A} = ' + sp.latex(create_matrix(G, form='signed'))))

## Stability analysis

In [7]:
display(Markdown(sign_stability(G).to_markdown(index=False)))

| Test          | Definition                                                                    | Result   |
|:--------------|:------------------------------------------------------------------------------|:---------|
| Condition i   | No positive self-effects                                                      | True     |
| Condition ii  | At least one node is self-regulating                                          | True     |
| Condition iii | The product of any pairwise interaction is non-positive                       | True     |
| Condition iv  | No cycles greater than length two                                             | False    |
| Condition v   | Non-zero determinant (all nodes have at least one incoming and outgoing link) | True     |
| Colour test   | Fails Jeffries' colour test                                                   | False    |
| Sign stable   | Satisfies necessary and sufficient conditions for sign stability              | False    |

In [8]:
display(Markdown(feedback_metrics(G).to_markdown(index=False)))

| Level   |   Net |   Absolute |   Positive |   Negative |   Weighted |
|:--------|------:|-----------:|-----------:|-----------:|-----------:|
| $F_{0}$ |    -1 |          1 |          0 |          1 |  -1        |
| $F_{1}$ |    -3 |          3 |          0 |          3 |  -1        |
| $F_{2}$ |   -13 |         13 |          0 |         13 |  -1        |
| $F_{3}$ |   -24 |         26 |          1 |         25 |  -0.923077 |
| $F_{4}$ |   -41 |         53 |          6 |         47 |  -0.773585 |
| $F_{5}$ |   -39 |         69 |         15 |         54 |  -0.565217 |
| $F_{6}$ |   -30 |         74 |         22 |         52 |  -0.405405 |
| $F_{7}$ |   -12 |         56 |         22 |         34 |  -0.214286 |
| $F_{8}$ |    -2 |         18 |          8 |         10 |  -0.111111 |

In [9]:
display(Markdown(determinants_metrics(G).to_markdown(index=False)))

| Hurwitz determinant   |             Net |         Absolute |    Weighted |
|:----------------------|----------------:|-----------------:|------------:|
| $\Delta_{0}$          |      1          |      1           | 1           |
| $\Delta_{1}$          |      3          |      3           | 1           |
| $\Delta_{2}$          |     15          |     65           | 0.230769    |
| $\Delta_{3}$          |    108          |   2374           | 0.0454928   |
| $\Delta_{4}$          |   1269          | 217929           | 0.005823    |
| $\Delta_{5}$          |  15309          |      2.31014e+07 | 0.000662686 |
| $\Delta_{6}$          | 140454          |      2.68841e+09 | 5.22442e-05 |
| $\Delta_{7}$          | 975402          |      1.86503e+11 | 5.22996e-06 |
| $\Delta_{8}$          |      1.9508e+06 |      3.35705e+12 | 5.81107e-07 |

In [10]:
display(Markdown(conditional_stability(G).to_markdown(index=False)))

| Test                    | Definition                                                | Result    |
|:------------------------|:----------------------------------------------------------|:----------|
| Weighted feedback       | Maximum weighted feedback (level 8)                       | -0.11     |
| Weighted determinant    | n-1 weighted determinant at level                         | 0.0000052 |
| Ratio to model-c system | Ratio to a 'model-c' type system                          | 16        |
| Model class             | Class of the model based on conditional stability metrics | Class I   |

In [11]:
display(Markdown(simulation_stability(G, n_sim=10000).to_markdown(index=False)))

| Test                      | Definition                                                            | Result   |
|:--------------------------|:----------------------------------------------------------------------|:---------|
| Stable matrices           | Proportion where all eigenvalues have negative real parts             | 35.22%   |
| Unstable matrices         | Proportion where one or more eigenvalues have positive real parts     | 64.78%   |
| Hurwitz criterion i       | Proportion where polynomial coefficients are not all of the same sign | 38.71%   |
| Hurwitz criterion ii      | Proportion where Hurwitz determinants are not all positive            | 49.00%   |
| Hurwitz criterion i only  | Proportion where only Hurwitz criterion i fails                       | 15.78%   |
| Hurwitz criterion ii only | Proportion where only Hurwitz criterion ii fails                      | 26.07%   |

## Press perturbation analysis

In [12]:
from IPython.display import display, Math
display(Math(r'\text{adj}(-^{\circ}\mathbf{A}) = ' + sp.latex(adjoint_matrix(G, form='signed'))))

In [13]:
display(Math(r'\mathbf{T} = ' + sp.latex(absolute_feedback_matrix(G))))

In [14]:
display(Math(r'\mathbf{W} = ' + sp.latex(weighted_predictions_matrix(G, as_abs=True).evalf(2))))

In [15]:
display(Math(r'\Pr\left(\text{sign}[\text{adj}(-^\circ\mathbf{A})] = \text{sign}[\text{adj}(-^\#\mathbf{A})]\right) = '))
sign_determinacy_matrix(G, method='average', as_abs=True).evalf(2)

⎡1.0   0.63  0.6   1.0   0.5   1.0   0.67  0.5 ⎤
⎢                                              ⎥
⎢0.63  0.83  0.89  0.63  0.86  0.63  0.93  0.86⎥
⎢                                              ⎥
⎢0.6   0.6   0.74  0.6   0.86  0.6   0.78  0.86⎥
⎢                                              ⎥
⎢1.0   0.63  0.6   0.56  0.5   1.0   0.67  0.5 ⎥
⎢                                              ⎥
⎢0.5   0.86  0.86  0.5   0.5   0.5   0.5   0.5 ⎥
⎢                                              ⎥
⎢1.0   0.63  0.78  1.0   0.5   1.0   0.67  0.5 ⎥
⎢                                              ⎥
⎢0.67  0.63  0.78  0.67  0.5   0.67  0.74  0.72⎥
⎢                                              ⎥
⎣0.5   0.86  0.86  0.5   0.5   0.5   0.72  0.5 ⎦

In [16]:
display(Math(r'\Pr\left(\text{sgn}\left[-{^\#\mathbf{A}}^{-1}\right]\right) = '))
numerical_simulations(G, n_sim=10000, dist="uniform", as_abs=True).evalf(2)

⎡1.0   0.69  0.62  1.0   0.56  1.0   0.63  0.56⎤
⎢                                              ⎥
⎢0.65  0.91  0.98  0.65  0.84  0.65  0.96  0.84⎥
⎢                                              ⎥
⎢0.76  0.65  0.84  0.76  0.91  0.75  0.82  0.91⎥
⎢                                              ⎥
⎢1.0   0.69  0.62  0.9   0.56  1.0   0.63  0.56⎥
⎢                                              ⎥
⎢0.55  0.96  0.9   0.55  0.66  0.55  0.68  0.66⎥
⎢                                              ⎥
⎢1.0   0.69  0.85  1.0   0.56  1.0   0.63  0.56⎥
⎢                                              ⎥
⎢0.76  0.64  0.85  0.76  0.6   0.76  0.93  0.93⎥
⎢                                              ⎥
⎣0.55  0.96  0.9   0.55  0.66  0.55  0.83  0.66⎦

## Qualitative predictions

In [17]:
index, columns = get_nodes(G, 'state'), get_nodes(G, 'state')
display(Markdown("Qualitative predictions (prediction weights):"))
table_of_predictions(weighted_predictions_matrix(G), t1=0.5, t2=1, index=index, columns=columns)

Qualitative predictions (prediction weights):

    P   A1   A2 AP   H1 H2   C1   C2
P   +    ?    ?  −    ?  +    ?    ?
A1  ?    ?  (−)  ?  (−)  ?  (+)  (−)
A2  ?    ?    ?  ?  (+)  ?    ?  (+)
AP  +    ?    ?  ?    ?  +    ?    ?
H1  ?  (+)  (−)  ?    ?  ?    ?    ?
H2  +    ?    ?  −    ?  +    ?    ?
C1  ?    ?    ?  ?    ?  ?    ?    ?
C2  ?  (+)  (−)  ?    ?  ?    ?    ?

In [18]:
display(Markdown("Qualitative predictions (sign determinacy)"))
table_of_predictions(sign_determinacy_matrix(G), t1=0.8, t2=1, index=index, columns=columns)

Qualitative predictions (sign determinacy)

    P   A1   A2 AP   H1 H2   C1   C2
P   +    ?    ?  −    ?  +    ?    ?
A1  ?  (+)  (−)  ?  (−)  ?  (+)  (−)
A2  ?    ?    ?  ?  (+)  ?    ?  (+)
AP  +    ?    ?  ?    ?  +    ?    ?
H1  ?  (+)  (−)  ?    ?  ?    ?    ?
H2  +    ?    ?  −    ?  +    ?    ?
C1  ?    ?    ?  ?    ?  ?    ?    ?
C2  ?  (+)  (−)  ?    ?  ?    ?    ?

In [19]:
index, columns = get_nodes(G, 'state'), get_nodes(G, 'state')
display(Markdown("Qualitative predictions (numerical simulations):"))
table_of_predictions(numerical_simulations(G), t1=0.8, t2=1, index=index, columns=columns)

Qualitative predictions (numerical simulations):

    P   A1   A2   AP   H1 H2   C1   C2
P   +    ?    ?    −    ?  +    ?    ?
A1  ?  (+)  (−)    ?  (−)  ?  (+)  (−)
A2  ?    ?  (+)    ?  (+)  ?  (−)  (+)
AP  +    ?    ?  (+)    ?  +    ?    ?
H1  ?  (+)  (−)    ?    ?  ?    ?    ?
H2  +    ?  (+)    −    ?  +    ?    ?
C1  ?    ?  (−)    ?    ?  ?  (+)  (−)
C2  ?  (+)  (−)    ?    ?  ?  (+)    ?